stages:
    - build
    
image: gcc

variables:
  GIT_SUBMODULE_STRATEGY: recursive
    
before_script:
    # Install build dependencies
    - apt-get update
    
build:
    stage: build
    script:
        - make