stages:
    - build
    
image: gcc
    
before_script:
    # Install build dependencies
    - apt-get update
    - git submodule sync --recursive
    - git submodule update --init --recursive
    
build:
    stage: build
    script:
        - make