# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Glad_config = debug
  ImGui_config = debug
  Engine1_config = debug
  Application_config = debug
endif
ifeq ($(config),release)
  GLFW_config = release
  Glad_config = release
  ImGui_config = release
  Engine1_config = release
  Application_config = release
endif
ifeq ($(config),dist)
  GLFW_config = dist
  Glad_config = dist
  ImGui_config = dist
  Engine1_config = dist
  Application_config = dist
endif

PROJECTS := GLFW Glad ImGui Engine1 Application

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: GLFW Glad ImGui

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Engine1/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C Engine1/vendor/Glad -f Makefile config=$(Glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Engine1/vendor/imgui -f Makefile config=$(ImGui_config)
endif

Engine1: GLFW Glad ImGui
ifneq (,$(Engine1_config))
	@echo "==== Building Engine1 ($(Engine1_config)) ===="
	@${MAKE} --no-print-directory -C Engine1 -f Makefile config=$(Engine1_config)
endif

Application: Engine1 Glad
ifneq (,$(Application_config))
	@echo "==== Building Application ($(Application_config)) ===="
	@${MAKE} --no-print-directory -C Application -f Makefile config=$(Application_config)
endif

clean:
	@${MAKE} --no-print-directory -C Engine1/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Engine1/vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C Engine1/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Engine1 -f Makefile clean
	@${MAKE} --no-print-directory -C Application -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   ImGui"
	@echo "   Engine1"
	@echo "   Application"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"