name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Run premake5
    - uses: actions/checkout@v1
    - name: configure
    - run: cd vendor/bin/premake && echo hi   
