name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: wtf
      uses: actions/checkout@v1
      with: 
        submodules: true
    - name: configure
      run: |
        dir
        cd vendor/bin/premake
        dir
        ./premake5.exe
        cd ../../..
        dir
        cd Engine1/vendor
