name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: wtf
      uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@1.0.0
    - name: configure
      run: |
        dir
        cd vendor/bin/premake
        dir
        ./premake5.exe
        cd ../../..
        dir
