name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: wtf
      uses: actions/checkout@v1
    - name: configure
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive
        dir
        cd scripts
        dir
        ./Win-GenProjects.bat
        dir
        echo yeeeet
