name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: wtf
      uses: actions/checkout@v1
    - name: configure
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive
        cd scripts
        ./Win-MakeFiles.bat
        cd ..
        make
        echo yeeeeet
