name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Project Download
      uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Configure
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive
        cd scripts
        ./Win-GenProjects.bat
    - name: Run
      run: |
        msbuild IPS_demo_v2.sln
